updated assembly
Zubax/Sadulli pull request #16
Opened 2023-04-27 12:04 UTC by Zentrus

closes #15
- updated assembly guide
- replaced motor
- replaced thermistor specification
- updated Sadulli version
- updated Sadulli readme
- added Alakdan photos

need to update main README table for Alakdan

2023-04-27 17:00 UTC, pavel-kirienko requested changes
Some things in this list are not directly related to the motor replacement but are still necessary to do.

- [x] Replace UAVCAN with Cyphal and add links to telega.zubax.com
- [ ] We need to increase the hardware overcurrent protection resistance to 27k (R1 on the `connectors` board). There is no purpose in providing this information in the README.
- [ ] Remove all generated files from the repository. Repositories are meant to contain only source files. Everything that can be generated from the source files goes into documentation package releases.

2023-04-27 17:00 UTC, pavel-kirienko commented on README.md
> +KTY81/120 | KTY81/110, KTY81/121, KTY81/122, or KTY81/150
```suggestion
KTY81/120 | KTY81/110, KTY81/121, KTY81/122, KTY81/150, 102PS1J, 102PS1G
```

2023-04-27 17:00 UTC, pavel-kirienko commented on assembly_instructions/readme.md
> +Thermistor                    | 1     | KTY81/120; Alternatives: KTY81/110, KTY81/121, KTY81/122, or KTY81/150 | PTC thermistor with pre-soldered extension wires.
```suggestion
Thermistor                    | 1     | NXP KTY81/120, NXP KTY81/110, NXP KTY81/121, NXP KTY81/122, NXP KTY81/150, Littelfuse 102PS1J, or Littelfuse 102PS1G | PTC thermistor with pre-soldered extension wires.
```

2023-05-02 22:40 UTC, pavel-kirienko requested changes
I left two minor suggestions. Aide from that, the only remaining issue is to update the resistor I mentioned earlier.

2023-05-02 22:40 UTC, pavel-kirienko commented on assembly_instructions/readme.md
> +    * Remove the motor stopper.
```suggestion
    * Remove the motor retainer ring.
```

2023-05-02 22:40 UTC, pavel-kirienko commented on assembly_instructions/readme.md
> +    * Get 4 pieces of DIN 7984 4 mm (motor screws). Attach the motor to the top housing. Use threadlock.
```suggestion
    * Get 4 pieces of DIN 7984 4 mm (motor screws). Attach the motor to the top housing. Use threadlock glue.
```

2023-05-03 08:58 UTC, Zentrus commented
@abualkasim-bakeer can you increase the hardware overcurrent protection resistance to 27k (R1 on the connectors board) in eagle?

2023-05-03 09:53 UTC, abualkasim-bakeer commented
> @abualkasim-bakeer can you increase the hardware overcurrent protection resistance to 27k (R1 on the connectors board) in eagle?

Okay, I will check it after finishing Valenok. Or you need it urgent?

2023-05-06 08:56 UTC, abualkasim-bakeer commented
The required change is done.

2023-05-06 15:26 UTC, pavel-kirienko commented
@abualkasim-bakeer please open a pull request against this branch.

![Uploading image.png…]()

2023-05-08 11:34 UTC, pavel-kirienko approved these changes

2023-05-08 11:41 UTC, merged