initial import
Zubax/Sadulli pull request #4
Opened 2020-03-03 22:15 UTC by j3qq4hch

[Sadulli.pdf](https://github.com/Zubax/Sadulli/files/4283884/Sadulli.pdf)
Результат компиляции во вложении к этому посту

2020-03-04 20:28 UTC, j3qq4hch commented
[Sadulli.pdf](https://github.com/Zubax/Sadulli/files/4289530/Sadulli.pdf)
commit b617317

2020-03-06 19:30 UTC, dimracer requested changes

2020-03-06 19:30 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +Zubax Sadulli is a tightly integrated unit that contains a motor and its control electronics in a compact enclosure. Sadulli is a turn-key solution for propulsion systems for light unmanned aerial ap
Длина строки должна быть не более 120 символов. 
Эту строку следует разбить как минимум на 3 строки.

2020-03-06 19:30 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +Zubax Sadulli is a tightly integrated unit that contains a motor and its control electronics in a compact enclosure. Sadulli is a turn-key solution for propulsion systems for light unmanned aerial ap
```suggestion
Zubax Sadulli is a tightly integrated unit that contains a motor and its control electronics in a compact enclosure. Sadulli is a turn-key solution for propulsion systems for light unmanned aerial applications. It is based on the \mbox{Mitochondrik} control module. All hardware is open source and available on Github\footnote{\url{https://github.com/Zubax/sadulli}}.
```

2020-03-06 19:30 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +    \item The solder-free design facilitates in-field maintenance
```suggestion
    \item The solder-free design facilitates in-field maintenance.
```

2020-03-06 19:30 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +    \item 550 W continuous power output
Здесь и далее не хватает точек в конце предложения.

2020-03-06 19:30 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +Sadulli is a tightly integrated unit that contains an electric motor with a sensorless electronic speed controller in a single monolithic package. Sadulli supply package includes an integrated drive
Длина строки >120 символов.

2020-03-06 19:30 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +Sadulli is a tightly integrated unit that contains an electric motor with a sensorless electronic speed controller in a single monolithic package. Sadulli supply package includes an integrated drive
> Sadulli supply package includes an integrated drive and a propeller.

Вообще-то нет. Мы договорились, что Sadulli поставляется без пропеллера, но с винтами для его крепления из комплекта мотора. Пропеллер может поставляться как опция за отдельные деньги. Многие пользователи хотят поставить свои пропеллеры например от T-Motor.

2020-03-06 19:30 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +    Weight          & 228     & 128      & 62    & g    & Cables not included  \\
```suggestion
    Weight          & 228     & 128      & 62    & g    & Cables and propeller not included  \\
```

2020-03-06 19:30 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +Zubax Sadulli is fully UAVCAN compatible and enables easy integration into the end system by using a full set of standard UAVCAN Micro connectors\footnote{For more details refer to \url{https://uavca
Длина строки.

2020-03-08 20:09 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +Sadulli is a tightly integrated unit that contains an electric motor with a sensorless electronic speed controller in a single monolithic package. Sadulli supply package includes an integrated drive
не помню, чтобы мы о таком договаривались. И это, вообще говоря, неправильно. Какая-то определенная тяга может быть гарантирована только в случае, если пропеллер поставляется нами.

2020-03-12 08:42 UTC, pavel-kirienko commented
Добавьте, пожалуйста, PowerShell скрипт для сборки.

2020-03-12 08:44 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +Zubax Sadulli is a tightly integrated unit that contains a motor and its control electronics in a compact enclosure. Sadulli is a turn-key solution for propulsion systems for light unmanned aerial ap
+

2020-03-12 08:44 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +    \item The solder-free design facilitates in-field maintenance
Точки в этом списке не требуются
+

2020-03-12 08:44 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +    \item 550 W continuous power output
они и не нужны

2020-03-12 08:44 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +Sadulli is a tightly integrated unit that contains an electric motor with a sensorless electronic speed controller in a single monolithic package. Sadulli supply package includes an integrated drive
+

2020-03-12 08:45 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +Zubax Sadulli is fully UAVCAN compatible and enables easy integration into the end system by using a full set of standard UAVCAN Micro connectors\footnote{For more details refer to \url{https://uavca
+

2020-03-12 08:46 UTC, pavel-kirienko commented
У меня ваш документ не компилируется с ошибками синтаксиса. Я либо не те ключи использую (во избежание нужен скрипт, см. выше), либо вы не проверили текст перед коммитом. Я рекомендую обратиться к Клайду в канале #it с просьбой настроить автоматическую сборку в GitHub Actions с сохранением результатов в хранилище GitHub, чтобы всегда был доступ к последней собранной версии, и чтобы коммиты проверялись на корректность автоматически.

2020-03-12 08:58 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +    Weight          & 228     & 128      & 62    & g    & Cables not included  \\
+

2020-03-12 09:37 UTC, j3qq4hch commented
[Sadulli.pdf](https://github.com/Zubax/Sadulli/files/4323369/Sadulli.pdf)
commit 540084db4db15f67de9b9185e0b6abd6c768acf3

2020-03-12 16:16 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +Sadulli is a tightly integrated unit that contains an electric motor with a sensorless electronic speed controller in a single monolithic package. Sadulli supply package includes an integrated drive
Тогда следует сделать фото с пропеллером и изменить цены.

2020-03-13 18:08 UTC, pavel-kirienko commented
Спасибо, но необходимости в CI это не отменяет.

2020-03-16 14:13 UTC, j3qq4hch commented
Я внес немного изменений. Теперь должно собираться

2020-03-17 20:45 UTC, j3qq4hch commented
[Sadulli.pdf](https://github.com/Zubax/Sadulli/files/4345758/Sadulli.pdf)
commit c86b20f4c7984d3c1d1f9ff08906407adec75034

2020-03-18 10:53 UTC, dimracer submitted a review, later dismissed

2020-03-18 10:53 UTC, dimracer commented on datasheet/characteristics.tex
> +    Thrust in efficient mode\tnote{a}   & 700               & 1500              &   gf  \\
Обычно это называется `long endurance power range`.

2020-03-18 10:53 UTC, dimracer commented on datasheet/Zubax_Sadulli.tex
> +    Continuous power                    & 500               & 500               &   W   \\
Не хватает еще рабочего диапазона напряжений.

2020-03-18 10:53 UTC, dimracer commented on datasheet/characteristics.tex
> +Blinks once if at least one CAN frame was successfully transmitted or successfully received in the last 25 milliseconds.
Длина строки.

2020-03-18 10:53 UTC, dimracer commented on datasheet/characteristics.tex
> +             Color              & Status                              & Description                                      \\
Длина строки

2020-03-18 10:53 UTC, dimracer commented on datasheet/characteristics.tex
> +                                                                        or FLASH has been damaged.                       \\
Длина строки

2020-03-18 10:53 UTC, dimracer commented on datasheet/characteristics.tex
> +    \ShowColor{green} Green     & Boot canceled                       & The device firmware has not been properly signed \\
```suggestion
    \ShowColor{green} Green     & Boot canceled                       & The device firmware has not been properly signed. \\
```

2020-03-18 10:53 UTC, dimracer commented on datasheet/characteristics.tex
> +    \ShowColor{green} Green     & Boot canceled                       & The device firmware has not been properly signed \\
длина строки

2020-03-18 10:53 UTC, dimracer commented on datasheet/characteristics.tex
> +    \ShowColor{magenta} Magenta & Ready to boot                       & Glows after the device power-up or restart event
```suggestion
    \ShowColor{magenta} Magenta & Ready to boot                       & Glows after the device power-up or restart event.
```

2020-03-18 10:53 UTC, dimracer commented on datasheet/overview.tex
> +12-33.6 V (4–8S $\text{LiCoO}_\text{2}$ battery).
```suggestion
12-33.6 V (4--8S $\text{LiCoO}_\text{2}$ battery).
```

2020-03-18 10:53 UTC, dimracer commented on datasheet/overview.tex
> +to design sophisticated custom motor controllers using motor control technology – T\'elega,
```suggestion
to design sophisticated custom motor controllers using motor control technology T\'elega, 
```

2020-03-18 10:53 UTC, dimracer commented on datasheet/overview.tex
> +which integrates advanced control algorithms. This datasheet is focused only on the Sadulli Hardware.
```suggestion
which integrates advanced control algorithms. This datasheet is focused only on the Sadulli hardware.
```

2020-03-18 10:53 UTC, dimracer commented on datasheet/thrust_characteristics.tex
> +    \caption{Sadulli Piccino Thrust vs. Efficiency\label{Piccino_thrust_vs_efficiency}}
Непонятное название. На графике изображено `Specific thrust vs motor speed`

2020-03-18 10:53 UTC, dimracer commented on datasheet/thrust_characteristics.tex
> +    \caption{Sadulli Grosso Thrust vs. Efficiency\label{Grosso_thrust_vs_efficiency}}
Аналогично

2020-03-18 10:53 UTC, dimracer commented on datasheet/thrust_characteristics.tex
> +    \caption{Sadulli Piccino propeller thrust vs. RPM\label{Piccino_thrust}}
Подпись неверная

2020-03-18 10:53 UTC, dimracer commented on datasheet/thrust_characteristics.tex
> +    \caption{Sadulli Grosso propeller thrust vs. RPM\label{Grosso_thrust}}
Для всех наших китов и Sadulli должны быть представлены 3 графика:
- Тяга от мощности (или мощность от тяги).
- Скорость от мощности.
- Эффективность (Specific thrust) от скорости.

2020-03-19 14:50 UTC, pavel-kirienko commented
Пожалуйста, следуйте рекомендациям из https://kb.zubax.com/display/MAINKB/Zubax+LaTeX+coding+conventions. Сходу видно, что по меньшей мере вы не следуете рекомендациям по именованию меток (`\label{}`) в документе.

2020-03-26 13:34 UTC, j3qq4hch commented on datasheet/characteristics.tex
> +    Thrust in efficient mode\tnote{a}   & 700               & 1500              &   gf  \\
Первый раз вижу такое словосочетание. Мне кажется, оно менее понятно, чем текущее. Не думаю, что это изменение необходимо

2020-03-26 16:53 UTC, j3qq4hch commented on datasheet/overview.tex
> +which integrates advanced control algorithms. This datasheet is focused only on the Sadulli Hardware.
+

2020-03-26 16:54 UTC, j3qq4hch commented on datasheet/thrust_characteristics.tex
> +    \caption{Sadulli Grosso propeller thrust vs. RPM\label{Grosso_thrust}}
+

2020-03-26 16:54 UTC, j3qq4hch commented on datasheet/thrust_characteristics.tex
> +    \caption{Sadulli Piccino propeller thrust vs. RPM\label{Piccino_thrust}}
+

2020-03-26 16:54 UTC, j3qq4hch commented on datasheet/thrust_characteristics.tex
> +    \caption{Sadulli Grosso Thrust vs. Efficiency\label{Grosso_thrust_vs_efficiency}}
+

2020-03-26 16:57 UTC, j3qq4hch commented on datasheet/overview.tex
> +12-33.6 V (4–8S $\text{LiCoO}_\text{2}$ battery).
+

2020-03-26 16:58 UTC, j3qq4hch commented on datasheet/overview.tex
> +to design sophisticated custom motor controllers using motor control technology – T\'elega,
+

2020-03-26 17:02 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +    Continuous power                    & 500               & 500               &   W   \\
И правда

2020-04-18 12:45 UTC, dimracer approved these changes
(removed)

2020-04-21 11:45 UTC, j3qq4hch commented on datasheet/Zubax_Sadulli.tex
> +Sadulli is a tightly integrated unit that contains an electric motor with a sensorless electronic speed controller in a single monolithic package. Sadulli supply package includes an integrated drive
@pavel-kirienko Нужно еще одно мнение

2020-04-23 21:29 UTC, pavel-kirienko commented on datasheet/Zubax_Sadulli.tex
> +Sadulli is a tightly integrated unit that contains an electric motor with a sensorless electronic speed controller in a single monolithic package. Sadulli supply package includes an integrated drive
Мы действительно договорились об этом на созвоне. Писать о комплекте поставки в документации я большого смысла не вижу, ведь он может измениться, и не хотелось бы, чтобы его изменения инвалидировали документ. Мы вполне можем поставлять садули преднастроенным под рекомендуемый пропеллер, но пользователь может поставить свой, обновив предварительно параметры контура скорости подобающим образом.

2020-08-12 21:57 UTC, closed without merging